Category.create(name: "NASA", img: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/NASA_logo.svg/1237px-NASA_logo.svg.png")
Category.create(name: "Music", img: "http://www.i2clipart.com/cliparts/8/8/c/a/clipart-bass-clef-256x256-88ca.png")

Track.create(title: "Space Rain", artist: "Jeff Spacely", description: "A one of a kind recording of a storm in space. You may think it sounds a lot like an earth storm, but that's really just your opinion.", category_id: 1, url: "https://s3.amazonaws.com/the-golden-record/Birds%2C+Hyena%2C+Elephant.wav", length: nil, composer: nil)
Track.create(title: "Musical Elephants", artist: "Jeff Courwin", description: "A one of a kind recording of an elephant singing. You may think it sounds a lot like an elephant proper, but that's really just your opinion.", category_id: 2, url: "https://s3.amazonaws.com/the-golden-record/Birds%2C+Hyena%2C+Elephant.wav", length: nil, composer: nil)
Track.create(title: "Empty Chairs something", artist: "Jeff Spacely", description: "A one of a kind recording of a storm in space. You may think it sounds a lot like an earth storm, but that's really just your opinion.", category_id: 1, url: "https://s3.amazonaws.com/the-golden-record/Empty+Chairs+8_2014+2.mp3", length: nil, composer: nil)
Track.create(title: "Hello From Planet Earth", artist: "Jeff Courwin", description: "A one of a kind recording of an elephant singing. You may think it sounds a lot like an elephant proper, but that's really just your opinion.", category_id: 2, url: "https://s3.amazonaws.com/the-golden-record/English.au", length: nil, composer: nil)

Track.create(title: "Soul Jazz", artist: "Jeff Spacely", description: "A one of a kind recording of a storm in space. You may think it sounds a lot like an earth storm, but that's really just your opinion.", category_id: 1, url: "https://s3.amazonaws.com/the-golden-record/ReginaApp-+Soul+Jazz.mp3", length: nil, composer: nil)
Track.create(title: "Ballad", artist: "Jeff Courwin", description: "A one of a kind recording of an elephant singing. You may think it sounds a lot like an elephant proper, but that's really just your opinion.", category_id: 2, url: "https://s3.amazonaws.com/the-golden-record/ReginaApp-+Ballad.mp3", length: nil, composer: nil)

Track.create(title: "Swing", artist: "Jeff Spacely", description: "A one of a kind recording of a storm in space. You may think it sounds a lot like an earth storm, but that's really just your opinion.", category_id: 1, url: "https://s3.amazonaws.com/the-golden-record/ReginaApp-+Swing.mp3", length: nil, composer: nil)
Track.create(title: "Footsteps Heartbeats Laughter ", artist: "Jeff Courwin", description: "A one of a kind recording of an elephant singing. You may think it sounds a lot like an elephant proper, but that's really just your opinion.", category_id: 2, url: "https://s3.amazonaws.com/the-golden-record/Footsteps%2C+Heartbeat%2C+Laughter.wav", length: nil, composer: nil)
